name: Aderyn
description: Perform smart contract static analysis checks.
author: Cyfrin

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: code
  color: blue

# Define your inputs here.
inputs:
  fail-on:
    description: values can be - high, all
    required: false

  warn-on:
    description: values can be - high, all
    requried: false

runs:
  using: node20
  main: dist/index.js
